version: "3.2"

services:
  glpi:
    image: glpi10-test
    container_name : glpi
    hostname: glpi
    ports:
      - "8095:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/glpi:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Paris
    restart: always
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.glpi.rule=Host(`glpi-test.omniphar.com`)
        - traefik.http.routers.glpi.entrypoints=websecure
        - traefik.http.services.glpi.loadbalancer.server.port=80
        - traefik.http.routers.glpi.service=glpi
        - traefik.http.routers.glpi.tls=true
